// Generated by CoffeeScript 1.4.0
(function() {
  var CardSchema, mongoose;

  mongoose = require('mongoose');

  module.exports = CardSchema = new mongoose.Schema({
    gameId: String,
    type: String
  });

  CardSchema.statics.generateDeck = function(gameId, cb) {
    var Card,
      _this = this;
    Card = mongoose.model('Card', CardSchema);
    return Card.find({}, function(err, cards) {
      var card, count, deck, obj, _i, _j, _len, _ref;
      if (err) {
        return cb(err);
      }
      if (cards.length === 0) {
        deck = [];
        deck.push({
          type: 'weapon',
          name: 'Rusty Fork',
          damage: 1,
          description: 'poop',
          playCost: 0,
          useCost: 1
        });
        deck.push({
          type: 'weapon',
          name: 'Rusty Fork',
          damage: 1,
          description: 'poop',
          playCost: 0,
          useCost: 1
        });
        deck.push({
          type: 'weapon',
          name: 'Rusty Fork',
          damage: 1,
          description: 'poop',
          playCost: 0,
          useCost: 1
        });
        deck.push({
          type: 'weapon',
          name: 'Rusty Fork',
          damage: 1,
          description: 'poop',
          playCost: 0,
          useCost: 1
        });
        deck.push({
          type: 'weapon',
          name: 'Rusty Fork',
          damage: 1,
          description: 'poop',
          playCost: 0,
          useCost: 1
        });
        deck.push({
          type: 'weapon',
          name: 'Rusty Fork',
          damage: 1,
          description: 'poop',
          playCost: 0,
          useCost: 1
        });
        deck.push({
          type: 'weapon',
          name: 'Rusty Fork',
          damage: 1,
          description: 'poop',
          playCost: 0,
          useCost: 1
        });
        deck.push({
          type: 'weapon',
          name: 'Rusty Fork',
          damage: 1,
          description: 'poop',
          playCost: 0,
          useCost: 1
        });
        deck.push({
          type: 'weapon',
          name: 'Rusty Fork',
          damage: 1,
          description: 'poop',
          playCost: 0,
          useCost: 1
        });
        deck.push({
          type: 'weapon',
          name: 'Rusty Fork',
          damage: 1,
          description: 'poop',
          playCost: 0,
          useCost: 1
        });
        deck.push({
          type: 'weapon',
          name: 'Rusty Fork',
          damage: 1,
          description: 'poop',
          playCost: 0,
          useCost: 1
        });
        count = deck.length;
        for (_i = 0, _ref = count * .3; 0 <= _ref ? _i <= _ref : _i >= _ref; 0 <= _ref ? _i++ : _i--) {
          deck.push({
            type: 'crystal',
            name: 'Crystal',
            damage: 0,
            description: 'bling bling',
            playCost: 0,
            useCost: 0
          });
        }
        for (_j = 0, _len = deck.length; _j < _len; _j++) {
          obj = deck[_j];
          card = new Card(obj);
          card.gameId = gameId;
          card.save(function(err) {
            if (err) {
              return cb(err);
            } else {
              return cards.push(card);
            }
          });
        }
      }
      return cb(null, cards);
    });
  };

}).call(this);
