// Generated by CoffeeScript 1.4.0
(function() {
  var CardSchema, mongoose;

  mongoose = require('mongoose');

  module.exports = CardSchema = new mongoose.Schema({
    gameId: String,
    type: String
  });

}).call(this);
