// Generated by CoffeeScript 1.4.0
(function() {
  var mongoose;

  mongoose = require('mongoose');

  module.exports = new mongoose.Schema({
    key: String,
    players: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Player'
      }
    ]
  });

}).call(this);
