// Generated by CoffeeScript 1.4.0
(function() {
  var GameSchema, mongoose;

  mongoose = require('mongoose');

  module.exports = GameSchema = new mongoose.Schema({
    gameId: String,
    players: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Player'
      }
    ],
    cards: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Cards'
      }
    ]
  });

  GameSchema.methods.init = function(cb) {
    var Card,
      _this = this;
    Card = mongoose.model('Card');
    return Card.generateDeck(this.gameId, function(err, card) {
      var _i, _len;
      if (err) {
        return cb(err);
      }
      _this.cards = [];
      for (_i = 0, _len = cards.length; _i < _len; _i++) {
        card = cards[_i];
        _this.cards.push(card.id);
      }
      return cb(null);
    });
  };

}).call(this);
