// Generated by CoffeeScript 1.4.0
(function() {
  var EventSchema, GameSchema, PlayerSchema, dbConfig, mongoose;

  mongoose = require('mongoose');

  dbConfig = require('./config');

  GameSchema = require('./GameSchema');

  PlayerSchema = require('./PlayerSchema');

  EventSchema = require('./EventSchema');

  exports.db = mongoose.createConnection(dbConfig.url);

  exports.GameModel = this.db.model('Game', GameSchema);

  exports.PlayerModel = this.db.model('Player', PlayerSchema);

  exports.EventModel = this.db.model('Event', EventSchema);

}).call(this);
