// Generated by CoffeeScript 1.4.0
(function() {
  var CardSchema, EventSchema, GameSchema, PlayerSchema, TileSchema, dbConfig, mongoose;

  mongoose = require('mongoose');

  dbConfig = require('./config');

  GameSchema = require('./GameSchema');

  PlayerSchema = require('./PlayerSchema');

  EventSchema = require('./EventSchema');

  CardSchema = require('./CardSchema');

  TileSchema = require('./TileSchema');

  exports.db = mongoose.createConnection(dbConfig.url);

  exports.GameModel = this.db.model('Game', GameSchema);

  exports.PlayerModel = this.db.model('Player', PlayerSchema);

  exports.EventModel = this.db.model('Event', EventSchema);

  exports.CardModel = this.db.model('Card', CardSchema);

  exports.TileModel = this.db.model('Tile', TileSchema);

}).call(this);
