// Generated by CoffeeScript 1.4.0
(function() {
  var mongoose;

  mongoose = require('mongoose');

  module.exports = new mongoose.Schema({
    _game: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Game'
    },
    name: String
  });

}).call(this);
