// Generated by CoffeeScript 1.4.0
(function() {
  var TileSchema, mongoose;

  mongoose = require('mongoose');

  module.exports = TileSchema = new mongoose.Schema({
    gameId: String,
    card: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Card'
    },
    player: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Player'
    },
    positionX: Number,
    positionY: Number,
    cardPickup: {
      type: Boolean,
      "default": false
    }
  });

  TileSchema.statics.generateBoard = function(gameId, cb) {
    var Tile, cardPickup, cols, rows, tile, tiles, x, y, _i, _j;
    Tile = mongoose.model('Tile', TileSchema);
    rows = 6;
    cols = 9;
    tiles = [];
    for (y = _i = 0; 0 <= rows ? _i <= rows : _i >= rows; y = 0 <= rows ? ++_i : --_i) {
      for (x = _j = 0; 0 <= cols ? _j <= cols : _j >= cols; x = 0 <= cols ? ++_j : --_j) {
        cardPickup = ((row + 2) % 5) + ((col + 2) % 5) === 0 ? true : false;
        tile = new Tile({
          gameId: gameId,
          positionX: x,
          positionY: y,
          cardPickup: cardPickup
        });
        tiles.push(tile);
        tile.save(function(err) {
          if (err) {
            cb(err);
            return;
          }
          return tiles.push(tile);
        });
      }
    }
    return cb(null, tiles);
  };

  mongoose.model('Tile', TileSchema);

}).call(this);
