// Generated by CoffeeScript 1.4.0
(function() {

  if (typeof window !== "undefined" && window !== null) {
    module.exports = window.Backbone;
  } else {
    module.exports = require('backbone');
  }

}).call(this);
