// Generated by CoffeeScript 1.4.0
(function() {
  var Card, Crystal,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Card = require('models/card');

  module.exports = Crystal = (function(_super) {

    __extends(Crystal, _super);

    function Crystal() {
      return Crystal.__super__.constructor.apply(this, arguments);
    }

    Crystal.prototype.initialize = function() {
      this.type = 'crystal';
      return this.energy = 0;
    };

    return Crystal;

  })(Card);

}).call(this);
