// Generated by CoffeeScript 1.4.0
(function() {
  var Backbone, Game, Tile,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Backbone = require('./backbone');

  Tile = require('./tile');

  module.exports = Game = (function(_super) {

    __extends(Game, _super);

    function Game() {
      return Game.__super__.constructor.apply(this, arguments);
    }

    Game.prototype.defaults = {
      gameId: '',
      tiles: []
    };

    Game.prototype.initialize = function() {
      var _this = this;
      return this.socket.on('game.boardSetup', function(data) {
        var obj, tile, _i, _len;
        for (_i = 0, _len = data.length; _i < _len; _i++) {
          obj = data[_i];
          tile = new Tile();
          tile.positionX = obj.positionX;
          tile.positionY = obj.positionY;
          if (obj.card) {
            tile.card = obj.card;
          }
          if (obj.player) {
            tile.player = obj.player;
          }
        }
        return _this.trigger('game.start');
      });
    };

    return Game;

  })(Backbone.Model);

}).call(this);
