// Generated by CoffeeScript 1.4.0
(function() {
  var Card, Spell,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Card = require('models/card');

  module.exports = Spell = (function(_super) {

    __extends(Spell, _super);

    function Spell() {
      return Spell.__super__.constructor.apply(this, arguments);
    }

    Spell.prototype.initialize = function() {
      return this.type = 'spell';
    };

    return Spell;

  })(Card);

}).call(this);
