// Generated by CoffeeScript 1.4.0
(function() {

  if (typeof window !== "undefined" && window !== null) {
    module.exports = window._;
  } else {
    module.exports = require('underscore');
  }

}).call(this);
