// Generated by CoffeeScript 1.4.0
(function() {
  var app, express, fs, path;

  express = require('express');

  path = require('path');

  fs = require('fs');

  module.exports = app = express();

  app.configure(function() {
    app.set('port', process.env.PORT || 8000);
    app.use(express.favicon());
    app.use(express.logger('dev'));
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(app.router);
    return app.use(express["static"](path.join(process.cwd(), 'public')));
  });

  app.configure('development', function() {
    return app.use(express.errorHandler());
  });

}).call(this);
